// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_app.tsx";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/Experience.tsx";
import * as $$1 from "./islands/Footer.tsx";
import * as $$2 from "./islands/Hero.tsx";
import * as $$3 from "./islands/Projects.tsx";
import * as $$4 from "./islands/Skills.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_app.tsx": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/Experience.tsx": $$0,
    "./islands/Footer.tsx": $$1,
    "./islands/Hero.tsx": $$2,
    "./islands/Projects.tsx": $$3,
    "./islands/Skills.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
